### ISSUE TITLE
Is ngInject a possible reason I get the following error?

### ISSUE THREAD

**Issue by paulsjv** [tniswong/web-build#12]
When I start `gulp preview` I get the following error in my console.  What's strange is that it was working fine and not it is not.  I haven't changed any part of this file(s) at all.  I was working on a different part of my app.  When I started with `gulp preview` I got the error below.  My gut is probably wrong but I was thinking that it may have to do with something not being picked up with the annotation of 'ngInject'? Here's the error below.

`Error: [$injector:unpr] Unknown provider: configProvider <- config <- configService <- dataService`

I've double checked spellings etc and like I have said I did not touch the file that is bootstrapping the application so I'm not sure what's causing the issue.

**Comment by tniswong** [comment]
Hard to tell without looking at it. My gut says probably not, and more likely something is misconfigured or missed during your last merge as I mentioned in your other issue #14

**Comment by tniswong** [comment]
Have a repo I can look at?

**Comment by paulsjv** [comment]
I was just working on getting everything merged.  Pull down the 2.0 branch and then `npm install` then `gulp preview` you'll see the error I'm talking about in the console.

https://github.com/paulsjv/leansheets/tree/2.0

**Comment by paulsjv** [comment]
I got it working.  Due to the change to `ngInject` one of my dependencies in the constructor was incorrect.  It should have bee `CONFIG` but was `config`.  This wasn't a problem when using:

```
static get $inject() {
    return ['$log','CONFIG'];
}

constructor ($log, config) {}
```

But since moving to `ngInject` and removing the `static` method the constructor needed to change to:

`constructor ($log, CONFIG)`

This matches the Angular context that was set when the application loaded.

**Comment by tniswong** [comment]
Nice, glad you figured it out.
