### ISSUE TITLE
Adding an angular controller to framework

### ISSUE THREAD

**Issue by paulsjv** [tniswong/web-build#5]
With your hello world directive it returns the following:

``` javascript
export default() => {
    return { ... }
```

However, when creating an angular controller and adding it to my module:

``` javascript
import appCtrl from './controllers/appCtrl';
ng.module('main', []).controller('appCtrl', appCtrl);
```

I get the following error:

> **Error: [ng:areq] Argument 'fn' is not a function, got Object**

My thought is that the appCtrl needs to return an array ( e.g. [ '$log', function($log) { ... } ] ) as seen in this example taken from [here](https://docs.angularjs.org/guide/directive):

``` javascript
angular.module('docsSimpleDirective', [])
.controller('Controller', ['$scope', function($scope) {
  $scope.customer = {
    name: 'Naomi',
    address: '1600 Amphitheatre'
  };
}])
```

My question is what should the export should be for the module to return what is expected from the .controller() call as I don't see any way to export an array?  If you have an example that would help.

**Comment by paulsjv** [comment]
Got this working correctly.  Now it seems that ng.bootstrap isn't bootstrapping the app as I can not get the application controller to respond.

**Comment by tniswong** [comment]
ES6 uses the same syntax for arrays as es5. 

Remember, `() => { }` is an "arrow function" that returns an object, aka an alias syntax for function literals. 

I can see how using `export default() => {}` might be confusing to people new to ES6, but think of it as `export default () => {}` instead. `default` here is not actually a named function, its a keyword.

Then think about substituting the function literal with an Array. IE: `export default []`.

Also, the example directive is the syntax for a directive, which should return a function that returns an object. For a controller, you should be returning an array. Perhaps you can submit a Controller example as a PR?

**Comment by paulsjv** [comment]
Great idea on the PR. I'll submit the one I have, but haven't gotten to work with bootstrap.

**Comment by paulsjv** [comment]
Also thanks for the explaination about ES6 and the `export default []` syntax.  Works like a charm!  Below is what I was doing before, which was very wrong.

**WRONG**

``` javascript

export default() =>
    return [ '$log','$scope', function($log, $scope) {
            $log.debug('in application controller!');
            $scope.click = function() {
                $log.debug('clicked!');
            };
        }];
}
```

**RIGHT**

``` javascript
export default [ '$log','$scope', function($log, $scope) {
            $log.debug('in application controller!');
            $scope.click = function() {
                $log.debug('clicked!');
            };
        }];
```
